
[build]
command = "bash ./scripts/netlify-build.sh"
publish = "dist"

[build.environment]
NODE_VERSION = "20"
NETLIFY_SKIP_SUBMODULE_CHECKOUT = "true"

# SPA (Vite/React) — evita 404 no refresh
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
