[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA (Vite/React) — evita 404 no refresh
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
